### ISSUE TITLE
Models API filter 'sorts': 'fallback_pledge_price' is not working

### ISSUE THREAD

**Issue by MarvinMiles** [fleetyards/fleetyards#360]
Hi!
Couple days ago  'sorts': 'fallback_pledge_price' stopped working

For now my example in previous issue #344 not working at all. Models just sorted by name.

How can I sort ships by pledge price?

**Comment by MarvinMiles** [comment]
@mortik ?

**Comment by MarvinMiles** [comment]
Hi @mortik 

New ships is not displayed in result list with **pledgePriceIn**  filter turned on.
Example:
https://www.fleetyards.net/ships?q%5BpledgePriceIn%5D%5B0%5D=75-100 -  **$80 Arrow** is not exist in the list.

 Same thing with **Valkiries** and **Mustang Alpha Vindicator**

**Comment by MarvinMiles** [comment]
Also sorting by fallback_pledge_price pushed this ships to end of the result list after $2500 Javelin

**Comment by mortik** [comment]
The Price for the Arrow should now be fixed. Thanks for reporting this :)

**Comment by MarvinMiles** [comment]
@mortik Valkyrie still doesn't work.

https://www.fleetyards.net/ships?q%5BpledgePriceIn%5D%5B0%5D=350-500

**Comment by mortik** [comment]
Valkyries and Mustang Alpha Vindicator should now also be fixed.
